// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPF0wJjeqSUwjNGGHssFQp7k3lAdyFEqc',
    appId: '1:516497946086:web:4f0788e1d2a00109391227',
    messagingSenderId: '516497946086',
    projectId: 'offline-toy',
    authDomain: 'offline-toy.firebaseapp.com',
    storageBucket: 'offline-toy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnuMi2vhcRMG3wINNXKEP1TVAX2HMsLM',
    appId: '1:516497946086:android:91c6998fbff9d943391227',
    messagingSenderId: '516497946086',
    projectId: 'offline-toy',
    storageBucket: 'offline-toy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5HIMHuHU-c6_ptNitIfbdH_XBhxy92M',
    appId: '1:516497946086:ios:7d1f646a419f4f42391227',
    messagingSenderId: '516497946086',
    projectId: 'offline-toy',
    storageBucket: 'offline-toy.appspot.com',
    iosClientId: '516497946086-03v9qfv9rf4mf431kk3u8q5jfi16vo5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.offlineToy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa5HIMHuHU-c6_ptNitIfbdH_XBhxy92M',
    appId: '1:516497946086:ios:7d1f646a419f4f42391227',
    messagingSenderId: '516497946086',
    projectId: 'offline-toy',
    storageBucket: 'offline-toy.appspot.com',
    iosClientId: '516497946086-03v9qfv9rf4mf431kk3u8q5jfi16vo5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.offlineToy',
  );
}
